spring.application.name=Interview_Service
spring.datasource.url=jdbc:mysql://host.docker.internal/ai_interview
spring.datasource.username=ai_interview
spring.datasource.password=ai_interview
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8003

logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG

#spring.grpc.server.port=9090
#spring.grpc.server.reflection.enabled=true
spring.grpc.server.enabled=false
spring.grpc.client.channels.getResponse.address=static://host.docker.internal:9091
spring.grpc.client.channels.getResponse.negotiation-type=plaintext

