import type { Metadata } from "next";
import AuthHeader from "@/components/AuthHeader";
import { Geist, Geist_Mono } from "next/font/google";
import SliderToggle from "@/components/SlidderToggle"; // Import Toggle
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ai Interview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <header className="flex justify-end p-4 gap-4 h-16">
          <SliderToggle />
          <AuthHeader />
        </header>
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
